export const languages = [
  { code: 'uz', label: 'UZ', name: "O‘zbekcha" },
  { code: 'ru', label: 'RU', name: 'Русский' },
  { code: 'en', label: 'EN', name: 'English' },
];

export const translations = {
  uz: {
    'common.currency': 'soʻm', 'common.perDay': '/ kun', 'common.day': 'kun', 'common.days': 'kun', 'common.guest': 'mehmon', 'common.guests': 'mehmon', 'common.quantity': 'Soni', 'common.date': 'Sana', 'common.price': 'Narx', 'common.total': 'Jami', 'common.subtotal': 'Oraliq jami', 'common.delivery': 'Yetkazib berish', 'common.installation': 'O‘rnatish', 'common.continue': 'Davom etish', 'common.cancel': 'Bekor qilish', 'common.remove': 'O‘chirish', 'common.save': 'Saqlash', 'common.close': 'Yopish', 'common.back': 'Orqaga', 'common.seeAll': 'Barchasini ko‘rish', 'common.search': 'Qidirish', 'common.all': 'Barchasi', 'common.active': 'Faol', 'common.paused': 'To‘xtatilgan', 'common.from': 'dan', 'common.optional': 'ixtiyoriy', 'common.required': 'Majburiy', 'common.browse': 'Ko‘rish', 'common.free': 'Bepul', 'common.items': 'mahsulot', 'common.item': 'mahsulot', 'common.details': 'Batafsil', 'common.status': 'Holati', 'common.perPerson': 'kishi boshiga', 'common.available': 'Mavjud', 'common.notAvailable': 'Mavjud emas', 'common.today': 'Bugun', 'common.goHome': 'Bosh sahifaga', 'common.send': 'Yuborish', 'common.update': 'Yangilash', 'common.noData': 'Hozircha ma’lumot yo‘q', 'common.rating': 'Reyting', 'common.reviews': 'sharh', 'common.menu': 'Menyu', 'common.apply': 'Qo‘llash', 'common.count': 'ta',

    'nav.home': 'Bosh sahifa', 'nav.equipment': 'Jihozlar', 'nav.services': 'Xizmatlar', 'nav.planner': 'Tadbirni rejalashtirish', 'nav.bookings': 'Buyurtmalarim', 'nav.cart': 'Savat', 'nav.account': 'Kabinet', 'nav.vendor': 'Hamkor kabineti', 'nav.admin': 'Admin paneli', 'nav.signIn': 'Kirish', 'nav.menu': 'Menyuni ochish',
    'header.delivery': 'Toshkent bo‘ylab yetkazib berish', 'header.member': 'Tadbirlar uchun ishonchli hamkor', 'header.language': 'Til',

    'hero.eyebrow': 'TADBIRLAR UCHUN BARCHASI BIR JOYDA', 'hero.title': "TADBIRINGIZNI 10 DAQIQADA YIG'ING", 'hero.subtitle': 'Kerakli jihoz va xizmatlarni toping, sanani belgilang va tadbiringizni ishonch bilan rejalashtiring.', 'hero.searchPlaceholder': 'Masalan, ovoz uskunasi yoki bezak', 'hero.searchButton': "Jihozlarni ko'rish", 'hero.date': 'Tadbir sanasi', 'hero.guests': 'Mehmonlar soni', 'hero.primaryCta': "Jihozlarni ko'rish", 'hero.secondaryCta': 'Tadbirni rejalashtirish', 'hero.rating': '4.9/5 mijozlar bahosi', 'hero.trust': 'Tadbir rejalashtirish endi oson', 'hero.trustNote': 'Tanlangan hamkorlar · Shaffof narxlar · O‘z vaqtida yetkazish', 'hero.badgeOne': 'Tadbirga tayyor', 'hero.badgeTwo': 'Top tanlov',

    'home.categoriesEyebrow': 'O‘ZINGIZGA KERAKLISINI TOPING', 'home.categoriesTitle': 'Har bir tadbirga mos yechim', 'home.categoriesText': 'To‘y, tug‘ilgan kun yoki korporativ uchrashuv — kerakli jihozlar bir necha qadamda.', 'home.popularEyebrow': 'MASHHUR TANLOVLAR', 'home.popularTitle': 'Ko‘p buyurtma qilinadigan jihozlar', 'home.popularText': 'Tadbir egalari sevib tanlayotgan, tekshirilgan mahsulotlar.', 'home.viewAll': 'Barcha jihozlar', 'home.stepsEyebrow': 'QANDAY ISHLAYDI?', 'home.stepsTitle': 'Rejalashtirish oson, bayram esa unutilmas', 'home.stepOneTitle': 'Tanlang', 'home.stepOneText': 'Kerakli jihoz va xizmatlarni katalogdan toping.', 'home.stepTwoTitle': 'Buyurtma bering', 'home.stepTwoText': 'Sana, miqdor va yetkazish usulini belgilang.', 'home.stepThreeTitle': 'Tadbirdan zavqlaning', 'home.stepThreeText': 'Hamkorlarimiz jihozlarni vaqtida olib keladi.', 'home.bannerTitle': 'Yaxshi tadbir — puxta rejaning natijasi', 'home.bannerText': 'Ovoz, yorug‘lik, mebel va bezaklarni bir savatda jamlang.', 'home.bannerCta': 'Rejani boshlash', 'home.reviewText': 'Buyurtma berish juda qulay bo‘ldi. Barcha jihozlar vaqtida yetib keldi va tadbirimiz ajoyib o‘tdi!', 'home.reviewBy': 'Madina R.', 'home.reviewRole': 'Toshkent · tug‘ilgan kun',

    'category.all': 'Barcha kategoriyalar', 'category.audio': 'Ovoz uskunalari', 'category.lighting': 'Yoritish', 'category.furniture': 'Mebel', 'category.decor': 'Bezak va sahna', 'category.photo': 'Foto va video', 'category.catering': 'Mehmon kutish',

    'catalog.eyebrow': 'FESTIVO KATALOGI', 'catalog.title': 'Tadbir jihozlari', 'catalog.subtitle': 'Tadbiringiz uchun kerakli jihozlarni toping va qulay narxda band qiling.', 'catalog.searchPlaceholder': 'Mahsulot yoki kategoriya qidirish', 'catalog.searchButton': 'Qidirish', 'catalog.filters': 'Filtrlar', 'catalog.category': 'Kategoriya', 'catalog.maxPrice': 'Maksimal narx', 'catalog.priceAny': 'Cheklov yo‘q', 'catalog.sort': 'Saralash', 'catalog.sortPopular': 'Mashhurlar avval', 'catalog.sortLow': 'Narx: arzonidan', 'catalog.sortHigh': 'Narx: qimmatidan', 'catalog.results': 'ta jihoz topildi', 'catalog.showing': 'Ko‘rsatilmoqda', 'catalog.emptyTitle': 'Hech narsa topilmadi', 'catalog.emptyText': 'Qidiruv so‘zini yoki filtrlarni o‘zgartirib ko‘ring.', 'catalog.clearFilters': 'Filtrlarni tozalash', 'catalog.mobileFilters': 'Filtrlar',

    'product.perDay': 'kuniga', 'product.addCart': "Savatga qo'shish", 'product.view': 'Batafsil', 'product.details': 'Mahsulot haqida', 'product.includes': 'To‘plam tarkibi', 'product.specs': 'Xususiyatlari', 'product.pickup': 'Olib ketish mumkin', 'product.deliveryAvailable': 'Yetkazib berish mavjud', 'product.chooseDate': 'Tadbir sanasini tanlang', 'product.quantity': 'Miqdori', 'product.rentalDays': 'Ijaraga olish muddati', 'product.chooseDateHint': 'Bandlik tanlangan sanaga qarab tekshiriladi.', 'product.stock': 'komplekt mavjud', 'product.vendor': 'Hamkor', 'product.reviews': 'mijoz bahosi', 'product.startingAt': 'Narxi', 'product.location': 'Toshkent, O‘zbekiston', 'product.guarantee': 'Toza va soz holatda topshiriladi', 'product.backCatalog': 'Katalogga qaytish', 'product.tagPopular': 'Mashhur', 'product.tagNew': 'Yangi', 'product.share': 'Ulashish', 'product.noDescription': 'Mahsulot haqida batafsil ma’lumot tez orada qo‘shiladi.', 'product.deliveryNote': 'Yetkazib berish narxi buyurtma yakunida ko‘rsatiladi.',

    'services.eyebrow': 'QO‘SHIMCHA QULAYLIK', 'services.title': 'Tadbir uchun xizmatlar', 'services.subtitle': 'Buyurtmangizga kerakli yordamni qo‘shing — hammasini bitta joydan boshqaring.', 'services.deliveryTitle': 'Yetkazib berish', 'services.deliveryText': 'Jihozlar tadbir manzilingizga kelishilgan vaqtda yetkaziladi.', 'services.installTitle': 'O‘rnatish va sozlash', 'services.installText': 'Mutaxassislar ovoz va yorug‘lik uskunalarini ulab, sozlab beradi.', 'services.supportTitle': 'Shaxsiy ko‘mak', 'services.supportText': 'Rejalashtirishda savolingiz bo‘lsa, jamoamiz yordam beradi.', 'services.browseCta': 'Jihoz tanlash', 'services.priceNote': 'Aniq xizmat narxi savatda hisoblanadi.',

    'planner.title': 'Tadbirni birgalikda rejalashtiramiz', 'planner.subtitle': 'Bir nechta ma’lumot kiriting — sizga mos jihozlarni taklif qilamiz.', 'planner.step': '1-qadam', 'planner.eventType': 'Qanday tadbir rejalashtiryapsiz?', 'planner.selectEvent': 'Tadbir turini tanlang', 'planner.date': 'Tadbir sanasi', 'planner.guests': 'Kutilayotgan mehmonlar', 'planner.venue': 'Tadbir manzili yoki joyi', 'planner.venuePlaceholder': 'Masalan, Toshkent shahri', 'planner.cta': 'Mos jihozlarni topish', 'planner.note': 'Rejangizni keyinroq savatda o‘zgartirishingiz mumkin.', 'planner.wedding': 'To‘y', 'planner.birthday': 'Tug‘ilgan kun', 'planner.corporate': 'Korporativ tadbir', 'planner.conference': 'Konferensiya', 'planner.concert': 'Konsert', 'planner.family': 'Oilaviy bayram',

    'cart.title': 'Savat', 'cart.subtitle': 'Tadbiringiz uchun tanlangan jihozlar.', 'cart.emptyTitle': 'Savatingiz hozircha bo‘sh', 'cart.emptyText': 'Katalogdan jihoz tanlang — ularni shu yerda ko‘rasiz.', 'cart.browse': 'Jihozlarni ko‘rish', 'cart.summary': 'Buyurtma xulosasi', 'cart.services': 'Qo‘shimcha xizmatlar', 'cart.deliveryLabel': 'Manzilga yetkazib berish', 'cart.deliveryHint': 'Jihozlarni tadbir manzilingizga olib kelamiz.', 'cart.installLabel': 'O‘rnatish va sozlash', 'cart.installHint': 'Mutaxassis jihozlarni ulab, sozlab beradi.', 'cart.deliveryFee': 'Yetkazib berish narxi', 'cart.installFee': 'O‘rnatish xizmati', 'cart.itemsTotal': 'Jihozlar jami', 'cart.checkout': 'Buyurtmani rasmiylashtirish', 'cart.freeDelivery': 'Yetkazib berish rasmiylashtirishda hisoblanadi.', 'cart.remove': 'Savatdan olib tashlash', 'cart.eventDate': 'Tadbir sanasi', 'cart.rentalDays': 'Ijara muddati', 'cart.secure': 'Xavfsiz buyurtma · yashirin to‘lovlarsiz', 'cart.editDate': 'Sanani o‘zgartiring',

    'checkout.title': 'Buyurtmani rasmiylashtirish', 'checkout.subtitle': 'Bog‘lanish va yetkazish ma’lumotlarini kiriting.', 'checkout.contactTitle': 'Aloqa ma’lumotlari', 'checkout.fullName': 'Ism va familiya', 'checkout.email': 'Elektron pochta', 'checkout.phone': 'Telefon raqami', 'checkout.address': 'Yetkazib berish manzili', 'checkout.eventDate': 'Tadbir sanasi', 'checkout.notes': 'Qo‘shimcha izoh', 'checkout.notesPlaceholder': 'Yetkazib berish bo‘yicha muhim ma’lumotlar', 'checkout.summary': 'Buyurtmangiz', 'checkout.placeOrder': 'Buyurtmani tasdiqlash', 'checkout.consent': 'Buyurtmani tasdiqlash orqali xizmat shartlariga rozilik bildirasiz.', 'checkout.requiredError': 'Iltimos, barcha majburiy maydonlarni to‘ldiring.', 'checkout.emailError': 'To‘g‘ri elektron pochta manzilini kiriting.', 'checkout.phoneError': 'To‘g‘ri telefon raqamini kiriting.', 'checkout.dateError': 'Tadbir sanasi bugun yoki undan keyin bo‘lishi kerak.', 'checkout.successTitle': 'Buyurtmangiz qabul qilindi!', 'checkout.successText': 'Hamkorimiz tez orada siz bilan bog‘lanadi. Buyurtma holatini shaxsiy kabinetingizda kuzatishingiz mumkin.', 'checkout.orderNumber': 'Buyurtma raqami', 'checkout.viewBookings': 'Buyurtmalarimni ko‘rish', 'checkout.continueShopping': 'Xaridni davom ettirish', 'checkout.deliveryMethod': 'Yetkazish usuli', 'checkout.deliveryAddress': 'Manzilga yetkazish', 'checkout.pickup': 'O‘zim olib ketaman', 'checkout.installation': 'O‘rnatish va sozlash xizmatini qo‘shish',

    'bookings.title': 'Buyurtmalarim', 'bookings.subtitle': 'Barcha buyurtmalaringiz va ularning holati shu yerda.', 'bookings.emptyTitle': 'Hali buyurtmalaringiz yo‘q', 'bookings.emptyText': 'Birinchi tadbiringizni rejalashtirish uchun katalogni ko‘ring.', 'bookings.browse': 'Jihozlarni ko‘rish', 'bookings.order': 'Buyurtma', 'bookings.created': 'Yaratildi', 'bookings.eventDate': 'Tadbir sanasi', 'bookings.guests': 'Mehmonlar', 'bookings.viewDetails': 'Tafsilotlarni ko‘rish', 'bookings.items': 'mahsulot', 'status.pending': 'Tasdiq kutilmoqda', 'status.confirmed': 'Tasdiqlandi', 'status.preparing': 'Tayyorlanmoqda', 'status.delivered': 'Yetkazildi', 'status.completed': 'Yakunlandi', 'status.cancelled': 'Bekor qilindi',

    'account.title': 'Shaxsiy kabinet', 'account.subtitle': 'Profilingiz va buyurtmalaringizni bir joydan boshqaring.', 'account.profile': 'Profil ma’lumotlari', 'account.signIn': 'Hisobga kirish', 'account.createAccount': 'Hisob yaratish', 'account.welcome': 'Xush kelibsiz, {name}!', 'account.savedProfile': 'Profil ma’lumotlaringiz saqlandi.', 'account.fullName': 'Ism va familiya', 'account.email': 'Elektron pochta', 'account.phone': 'Telefon raqami', 'account.address': 'Manzil', 'account.orders': 'Buyurtmalar', 'account.notifications': 'Bildirishnomalar', 'account.notificationsText': 'Buyurtma holati yangilanganda sizga xabar beramiz.', 'account.memberSince': 'FESTIVO bilan', 'account.signInButton': 'Kirish', 'account.logout': 'Chiqish', 'account.note': 'Hozircha test kabinet: profil ma’lumotlari ushbu qurilmada saqlanadi.', 'account.guest': 'Mehmon foydalanuvchi', 'account.profileSaved': 'Profil saqlandi',

    'vendor.title': 'Hamkor kabineti', 'vendor.subtitle': 'Jihozlaringizni boshqaring va buyurtmalarni kuzating.', 'vendor.dashboard': 'Umumiy ko‘rinish', 'vendor.addListing': 'Yangi taklif qo‘shish', 'vendor.addListingText': 'Jihozingizni katalogga joylang va ko‘proq mijozlarga yetib boring.', 'vendor.listingName': 'Jihoz nomi', 'vendor.listingCategory': 'Kategoriya', 'vendor.listingPrice': 'Kunlik ijara narxi', 'vendor.listingDescription': 'Qisqa tavsif', 'vendor.descriptionPlaceholder': 'Jihoz haqida muhim ma’lumotlar', 'vendor.addListingButton': 'Taklifni joylash', 'vendor.myListings': 'Mening takliflarim', 'vendor.available': 'Faol takliflar', 'vendor.rented': 'Buyurtmalar', 'vendor.revenue': 'Taxminiy tushum', 'vendor.productStatus': 'Holati', 'vendor.pause': 'To‘xtatish', 'vendor.activate': 'Faollashtirish', 'vendor.noListings': 'Hozircha takliflaringiz yo‘q. Birinchi jihozingizni qo‘shing.', 'vendor.verification': 'Hamkor maqomi', 'vendor.verified': 'Tasdiqlangan hamkor', 'vendor.orders': 'Buyurtmalar', 'vendor.saveListing': 'Taklifni saqlash', 'vendor.help': 'Savol bormi? FESTIVO hamkorlar jamoasi sizga yordam beradi.', 'vendor.noOrders': 'Hozircha yangi buyurtma yo‘q.', 'vendor.created': 'Yangi taklif katalogga qo‘shildi.', 'vendor.userTitle': 'Hamkor taklifi', 'vendor.userDescription': 'Yangi jihoz va xizmat.',

    'admin.title': 'Admin paneli', 'admin.subtitle': 'FESTIVO marketplace faoliyatini nazorat qiling.', 'admin.overview': 'Umumiy ko‘rsatkichlar', 'admin.totalOrders': 'Buyurtmalar', 'admin.totalVendors': 'Hamkorlar', 'admin.totalListings': 'Faol takliflar', 'admin.grossVolume': 'Buyurtmalar qiymati', 'admin.recentOrders': 'So‘nggi buyurtmalar', 'admin.manageListings': 'Katalog takliflari', 'admin.manageBookings': 'Buyurtmalarni boshqarish', 'admin.orderId': 'Raqam', 'admin.customer': 'Mijoz', 'admin.event': 'Tadbir sanasi', 'admin.payment': 'Jami', 'admin.action': 'Amal', 'admin.approve': 'Tasdiqlash', 'admin.reject': 'Yashirish', 'admin.confirm': 'Buyurtmani tasdiqlash', 'admin.markDelivered': 'Yetkazildi deb belgilash', 'admin.noOrders': 'Hozircha buyurtmalar mavjud emas.', 'admin.note': 'Admin panelidagi amallar brauzer xotirasida saqlanadi.', 'admin.listingActive': 'Katalogda', 'admin.listingPaused': 'Yashirilgan', 'admin.completeBooking': 'Yakunlangan deb belgilash',

    'footer.tagline': 'Tadbirlaringizni oson va ishonch bilan rejalashtiring.', 'footer.explore': 'Kashf eting', 'footer.support': 'Yordam', 'footer.company': 'FESTIVO', 'footer.helpCenter': 'Yordam markazi', 'footer.howWorks': 'Qanday ishlaydi', 'footer.about': 'Biz haqimizda', 'footer.terms': 'Foydalanish shartlari', 'footer.privacy': 'Maxfiylik siyosati', 'footer.contact': 'Aloqa', 'footer.copyright': 'Barcha huquqlar himoyalangan.', 'footer.madeWith': 'Tadbirlar uchun mehr bilan', 'footer.newsletter': 'Yangiliklardan xabardor bo‘ling', 'footer.newsletterText': 'Yangi takliflar va foydali maslahatlar — vaqti-vaqti bilan pochta qutingizda.', 'footer.emailPlaceholder': 'Elektron pochtangiz', 'footer.subscribe': 'Obuna bo‘lish', 'footer.newsletterSuccess': 'Obuna uchun rahmat!', 'legal.aboutTitle': 'FESTIVO haqida', 'legal.aboutText': 'FESTIVO — tadbirlar uchun jihoz va xizmatlarni topish, solishtirish va band qilishga yordam beradigan marketplace. Mahalliy hamkorlar, aniq narxlar va qulay rejalashtirishni bir joyga jamlaymiz.', 'legal.termsTitle': 'Foydalanish shartlari', 'legal.termsText': 'FESTIVO mahsulot va xizmatlarni topish hamda buyurtma berish uchun platforma taqdim etadi. Buyurtma yuborilgach, hamkor mavjudlik va yetkazish tafsilotlarini tasdiqlash uchun siz bilan bog‘lanadi. Ushbu demo versiyada ma’lumotlar faqat qurilmangizda saqlanadi.', 'legal.privacyTitle': 'Maxfiylik siyosati', 'legal.privacyText': 'Ushbu demo profil, savat va buyurtmalaringizni brauzeringiz xotirasida saqlaydi. Ma’lumotlaringiz serverga yuborilmaydi. Mahsulot versiyasida ma’lumotlarni himoya qilish va o‘chirish bo‘yicha aniq tartiblar taqdim etiladi.', 'legal.helpTitle': 'Yordam markazi', 'legal.helpText': 'Buyurtma, jihoz tanlash yoki tadbir rejangiz bo‘yicha savolingiz bormi? FESTIVO jamoasiga yozing — biz yordam berishga tayyormiz.', 'legal.contactEmail': 'hello@festivo.uz',

    'toast.added': 'Jihoz savatga qo‘shildi.', 'toast.removed': 'Jihoz savatdan olib tashlandi.', 'toast.bookingCreated': 'Buyurtma muvaffaqiyatli yaratildi.', 'toast.profileSaved': 'Profil saqlandi.', 'toast.listingAdded': 'Yangi taklif qo‘shildi.', 'toast.listingStatus': 'Taklif holati yangilandi.', 'toast.bookingUpdated': 'Buyurtma holati yangilandi.', 'toast.langChanged': 'Til o‘zgartirildi.', 'toast.copied': 'Havola nusxalandi.', 'toast.newsletter': 'Obuna uchun rahmat!',

    'validation.name': 'Ism va familiyangizni kiriting.', 'validation.email': 'To‘g‘ri elektron pochta manzilini kiriting.', 'validation.phone': 'Telefon raqamini kiriting.', 'validation.date': 'Tadbir sanasini tanlang.', 'validation.datePast': 'Sana bugun yoki undan keyin bo‘lishi kerak.', 'validation.quantity': 'Miqdor kamida 1 bo‘lishi kerak.', 'validation.terms': 'Davom etish uchun shartlarga rozilik bildiring.', 'validation.price': 'Narx 0 dan katta bo‘lishi kerak.', 'validation.category': 'Kategoriyani tanlang.', 'validation.listingTitle': 'Jihoz nomini kiriting.', 'validation.listingDescription': 'Jihoz tavsifini kiriting.', 'validation.address': 'Yetkazib berish manzilini kiriting.',
  },

  ru: {
    'common.currency': 'сум', 'common.perDay': '/ день', 'common.day': 'день', 'common.days': 'дн.', 'common.guest': 'гость', 'common.guests': 'гостей', 'common.quantity': 'Количество', 'common.date': 'Дата', 'common.price': 'Цена', 'common.total': 'Итого', 'common.subtotal': 'Промежуточный итог', 'common.delivery': 'Доставка', 'common.installation': 'Установка', 'common.continue': 'Продолжить', 'common.cancel': 'Отмена', 'common.remove': 'Удалить', 'common.save': 'Сохранить', 'common.close': 'Закрыть', 'common.back': 'Назад', 'common.seeAll': 'Смотреть всё', 'common.search': 'Поиск', 'common.all': 'Все', 'common.active': 'Активно', 'common.paused': 'Приостановлено', 'common.from': 'от', 'common.optional': 'необязательно', 'common.required': 'Обязательно', 'common.browse': 'Смотреть', 'common.free': 'Бесплатно', 'common.items': 'товаров', 'common.item': 'товар', 'common.details': 'Подробнее', 'common.status': 'Статус', 'common.perPerson': 'на человека', 'common.available': 'В наличии', 'common.notAvailable': 'Нет в наличии', 'common.today': 'Сегодня', 'common.goHome': 'На главную', 'common.send': 'Отправить', 'common.update': 'Обновить', 'common.noData': 'Пока нет данных', 'common.rating': 'Рейтинг', 'common.reviews': 'отзывов', 'common.menu': 'Меню', 'common.apply': 'Применить', 'common.count': 'шт.',

    'nav.home': 'Главная', 'nav.equipment': 'Оборудование', 'nav.services': 'Услуги', 'nav.planner': 'Планировать мероприятие', 'nav.bookings': 'Мои заказы', 'nav.cart': 'Корзина', 'nav.account': 'Кабинет', 'nav.vendor': 'Кабинет партнёра', 'nav.admin': 'Панель администратора', 'nav.signIn': 'Войти', 'nav.menu': 'Открыть меню',
    'header.delivery': 'Доставка по Ташкенту', 'header.member': 'Надёжный партнёр для событий', 'header.language': 'Язык',

    'hero.eyebrow': 'ВСЁ ДЛЯ МЕРОПРИЯТИЯ В ОДНОМ МЕСТЕ', 'hero.title': 'ОРГАНИЗУЙТЕ МЕРОПРИЯТИЕ ЗА 10 МИНУТ', 'hero.subtitle': 'Найдите оборудование и услуги, выберите дату и планируйте праздник с уверенностью.', 'hero.searchPlaceholder': 'Например, звуковое оборудование или декор', 'hero.searchButton': 'Посмотреть оборудование', 'hero.date': 'Дата мероприятия', 'hero.guests': 'Количество гостей', 'hero.primaryCta': 'Посмотреть оборудование', 'hero.secondaryCta': 'Планировать мероприятие', 'hero.rating': 'Оценка клиентов 4,9/5', 'hero.trust': 'Планировать событие теперь легко', 'hero.trustNote': 'Проверенные партнёры · Прозрачные цены · Доставка вовремя', 'hero.badgeOne': 'Готово к событию', 'hero.badgeTwo': 'Популярный выбор',

    'home.categoriesEyebrow': 'НАЙДИТЕ ТО, ЧТО НУЖНО', 'home.categoriesTitle': 'Решения для любого события', 'home.categoriesText': 'Свадьба, день рождения или корпоратив — нужное оборудование в несколько шагов.', 'home.popularEyebrow': 'ПОПУЛЯРНЫЙ ВЫБОР', 'home.popularTitle': 'Часто заказывают', 'home.popularText': 'Проверенное оборудование, которое выбирают организаторы.', 'home.viewAll': 'Всё оборудование', 'home.stepsEyebrow': 'КАК ЭТО РАБОТАЕТ?', 'home.stepsTitle': 'Планировать легко, а праздник запомнится надолго', 'home.stepOneTitle': 'Выберите', 'home.stepOneText': 'Найдите оборудование и услуги в каталоге.', 'home.stepTwoTitle': 'Оформите заказ', 'home.stepTwoText': 'Укажите дату, количество и способ доставки.', 'home.stepThreeTitle': 'Наслаждайтесь событием', 'home.stepThreeText': 'Наши партнёры доставят всё вовремя.', 'home.bannerTitle': 'Хорошее событие начинается с плана', 'home.bannerText': 'Соберите звук, свет, мебель и декор в одной корзине.', 'home.bannerCta': 'Начать планирование', 'home.reviewText': 'Заказывать было очень удобно. Всё оборудование привезли вовремя, и наш праздник прошёл замечательно!', 'home.reviewBy': 'Мадина Р.', 'home.reviewRole': 'Ташкент · день рождения',

    'category.all': 'Все категории', 'category.audio': 'Звуковое оборудование', 'category.lighting': 'Освещение', 'category.furniture': 'Мебель', 'category.decor': 'Декор и сцена', 'category.photo': 'Фото и видео', 'category.catering': 'Угощения',

    'catalog.eyebrow': 'КАТАЛОГ FESTIVO', 'catalog.title': 'Оборудование для событий', 'catalog.subtitle': 'Найдите нужное оборудование и забронируйте его по удобной цене.', 'catalog.searchPlaceholder': 'Поиск по товарам и категориям', 'catalog.searchButton': 'Найти', 'catalog.filters': 'Фильтры', 'catalog.category': 'Категория', 'catalog.maxPrice': 'Максимальная цена', 'catalog.priceAny': 'Без ограничений', 'catalog.sort': 'Сортировка', 'catalog.sortPopular': 'Сначала популярные', 'catalog.sortLow': 'Сначала дешевле', 'catalog.sortHigh': 'Сначала дороже', 'catalog.results': 'товаров найдено', 'catalog.showing': 'Показано', 'catalog.emptyTitle': 'Ничего не найдено', 'catalog.emptyText': 'Измените поисковый запрос или фильтры.', 'catalog.clearFilters': 'Сбросить фильтры', 'catalog.mobileFilters': 'Фильтры',

    'product.perDay': 'в день', 'product.addCart': 'Добавить в корзину', 'product.view': 'Подробнее', 'product.details': 'О товаре', 'product.includes': 'В комплекте', 'product.specs': 'Характеристики', 'product.pickup': 'Можно забрать самостоятельно', 'product.deliveryAvailable': 'Доступна доставка', 'product.chooseDate': 'Выберите дату мероприятия', 'product.quantity': 'Количество', 'product.rentalDays': 'Срок аренды', 'product.chooseDateHint': 'Доступность проверяется для выбранной даты.', 'product.stock': 'комплектов доступно', 'product.vendor': 'Партнёр', 'product.reviews': 'оценок клиентов', 'product.startingAt': 'Цена', 'product.location': 'Ташкент, Узбекистан', 'product.guarantee': 'Передаётся в чистом и исправном состоянии', 'product.backCatalog': 'Вернуться в каталог', 'product.tagPopular': 'Популярное', 'product.tagNew': 'Новинка', 'product.share': 'Поделиться', 'product.noDescription': 'Подробная информация о товаре скоро появится.', 'product.deliveryNote': 'Стоимость доставки будет показана при оформлении.',

    'services.eyebrow': 'ДОПОЛНИТЕЛЬНОЕ УДОБСТВО', 'services.title': 'Услуги для мероприятия', 'services.subtitle': 'Добавьте нужную помощь к заказу и управляйте всем в одном месте.', 'services.deliveryTitle': 'Доставка', 'services.deliveryText': 'Привезём оборудование по адресу и к согласованному времени.', 'services.installTitle': 'Установка и настройка', 'services.installText': 'Специалисты подключат и настроят звуковое и световое оборудование.', 'services.supportTitle': 'Персональная помощь', 'services.supportText': 'Наша команда поможет, если у вас возникнут вопросы при планировании.', 'services.browseCta': 'Выбрать оборудование', 'services.priceNote': 'Точная стоимость услуг рассчитывается в корзине.',

    'planner.title': 'Спланируем мероприятие вместе', 'planner.subtitle': 'Укажите несколько деталей — и мы подберём подходящее оборудование.', 'planner.step': 'Шаг 1', 'planner.eventType': 'Какое мероприятие вы планируете?', 'planner.selectEvent': 'Выберите тип мероприятия', 'planner.date': 'Дата мероприятия', 'planner.guests': 'Ожидаемое количество гостей', 'planner.venue': 'Адрес или место мероприятия', 'planner.venuePlaceholder': 'Например, город Ташкент', 'planner.cta': 'Найти подходящее оборудование', 'planner.note': 'Вы сможете изменить план позже в корзине.', 'planner.wedding': 'Свадьба', 'planner.birthday': 'День рождения', 'planner.corporate': 'Корпоратив', 'planner.conference': 'Конференция', 'planner.concert': 'Концерт', 'planner.family': 'Семейный праздник',

    'cart.title': 'Корзина', 'cart.subtitle': 'Оборудование для вашего мероприятия.', 'cart.emptyTitle': 'В корзине пока пусто', 'cart.emptyText': 'Выберите оборудование в каталоге — оно появится здесь.', 'cart.browse': 'Посмотреть оборудование', 'cart.summary': 'Итого по заказу', 'cart.services': 'Дополнительные услуги', 'cart.deliveryLabel': 'Доставка по адресу', 'cart.deliveryHint': 'Привезём оборудование к месту мероприятия.', 'cart.installLabel': 'Установка и настройка', 'cart.installHint': 'Специалист подключит и настроит оборудование.', 'cart.deliveryFee': 'Стоимость доставки', 'cart.installFee': 'Услуга установки', 'cart.itemsTotal': 'Стоимость оборудования', 'cart.checkout': 'Оформить заказ', 'cart.freeDelivery': 'Стоимость доставки рассчитывается при оформлении.', 'cart.remove': 'Убрать из корзины', 'cart.eventDate': 'Дата мероприятия', 'cart.rentalDays': 'Срок аренды', 'cart.secure': 'Безопасный заказ · без скрытых платежей', 'cart.editDate': 'Изменить дату',

    'checkout.title': 'Оформление заказа', 'checkout.subtitle': 'Укажите контактные данные и адрес доставки.', 'checkout.contactTitle': 'Контактные данные', 'checkout.fullName': 'Имя и фамилия', 'checkout.email': 'Электронная почта', 'checkout.phone': 'Номер телефона', 'checkout.address': 'Адрес доставки', 'checkout.eventDate': 'Дата мероприятия', 'checkout.notes': 'Комментарий', 'checkout.notesPlaceholder': 'Важная информация о доставке', 'checkout.summary': 'Ваш заказ', 'checkout.placeOrder': 'Подтвердить заказ', 'checkout.consent': 'Подтверждая заказ, вы соглашаетесь с условиями сервиса.', 'checkout.requiredError': 'Пожалуйста, заполните все обязательные поля.', 'checkout.emailError': 'Укажите корректный адрес электронной почты.', 'checkout.phoneError': 'Укажите корректный номер телефона.', 'checkout.dateError': 'Дата мероприятия должна быть сегодня или позже.', 'checkout.successTitle': 'Ваш заказ принят!', 'checkout.successText': 'Партнёр скоро свяжется с вами. Статус заказа можно отслеживать в личном кабинете.', 'checkout.orderNumber': 'Номер заказа', 'checkout.viewBookings': 'Посмотреть мои заказы', 'checkout.continueShopping': 'Продолжить покупки', 'checkout.deliveryMethod': 'Способ получения', 'checkout.deliveryAddress': 'Доставка по адресу', 'checkout.pickup': 'Заберу самостоятельно', 'checkout.installation': 'Добавить установку и настройку',

    'bookings.title': 'Мои заказы', 'bookings.subtitle': 'Здесь собраны все ваши заказы и их статусы.', 'bookings.emptyTitle': 'У вас пока нет заказов', 'bookings.emptyText': 'Посмотрите каталог и спланируйте своё первое событие.', 'bookings.browse': 'Посмотреть оборудование', 'bookings.order': 'Заказ', 'bookings.created': 'Создан', 'bookings.eventDate': 'Дата мероприятия', 'bookings.guests': 'Гостей', 'bookings.viewDetails': 'Подробнее о заказе', 'bookings.items': 'товаров', 'status.pending': 'Ожидает подтверждения', 'status.confirmed': 'Подтверждён', 'status.preparing': 'Готовится', 'status.delivered': 'Доставлен', 'status.completed': 'Завершён', 'status.cancelled': 'Отменён',

    'account.title': 'Личный кабинет', 'account.subtitle': 'Управляйте профилем и заказами в одном месте.', 'account.profile': 'Данные профиля', 'account.signIn': 'Войти в аккаунт', 'account.createAccount': 'Создать аккаунт', 'account.welcome': 'Добро пожаловать, {name}!', 'account.savedProfile': 'Данные профиля сохранены.', 'account.fullName': 'Имя и фамилия', 'account.email': 'Электронная почта', 'account.phone': 'Номер телефона', 'account.address': 'Адрес', 'account.orders': 'Заказы', 'account.notifications': 'Уведомления', 'account.notificationsText': 'Мы сообщим вам об изменении статуса заказа.', 'account.memberSince': 'С FESTIVO с', 'account.signInButton': 'Войти', 'account.logout': 'Выйти', 'account.note': 'Демонстрационный кабинет: данные профиля сохраняются на этом устройстве.', 'account.guest': 'Гость', 'account.profileSaved': 'Профиль сохранён',

    'vendor.title': 'Кабинет партнёра', 'vendor.subtitle': 'Управляйте оборудованием и следите за заказами.', 'vendor.dashboard': 'Обзор', 'vendor.addListing': 'Добавить предложение', 'vendor.addListingText': 'Разместите оборудование в каталоге и найдите новых клиентов.', 'vendor.listingName': 'Название оборудования', 'vendor.listingCategory': 'Категория', 'vendor.listingPrice': 'Цена аренды за день', 'vendor.listingDescription': 'Краткое описание', 'vendor.descriptionPlaceholder': 'Важная информация об оборудовании', 'vendor.addListingButton': 'Опубликовать предложение', 'vendor.myListings': 'Мои предложения', 'vendor.available': 'Активные предложения', 'vendor.rented': 'Заказы', 'vendor.revenue': 'Ориентировочный доход', 'vendor.productStatus': 'Статус', 'vendor.pause': 'Приостановить', 'vendor.activate': 'Активировать', 'vendor.noListings': 'Пока нет предложений. Добавьте своё первое оборудование.', 'vendor.verification': 'Статус партнёра', 'vendor.verified': 'Проверенный партнёр', 'vendor.orders': 'Заказы', 'vendor.saveListing': 'Сохранить предложение', 'vendor.help': 'Есть вопросы? Команда FESTIVO поможет вам.', 'vendor.noOrders': 'Новых заказов пока нет.', 'vendor.created': 'Новое предложение добавлено в каталог.', 'vendor.userTitle': 'Предложение партнёра', 'vendor.userDescription': 'Новое оборудование и услуга.',

    'admin.title': 'Панель администратора', 'admin.subtitle': 'Управляйте работой маркетплейса FESTIVO.', 'admin.overview': 'Обзор показателей', 'admin.totalOrders': 'Заказы', 'admin.totalVendors': 'Партнёры', 'admin.totalListings': 'Активные предложения', 'admin.grossVolume': 'Сумма заказов', 'admin.recentOrders': 'Последние заказы', 'admin.manageListings': 'Предложения каталога', 'admin.manageBookings': 'Управление заказами', 'admin.orderId': 'Номер', 'admin.customer': 'Клиент', 'admin.event': 'Дата события', 'admin.payment': 'Итого', 'admin.action': 'Действие', 'admin.approve': 'Подтвердить', 'admin.reject': 'Скрыть', 'admin.confirm': 'Подтвердить заказ', 'admin.markDelivered': 'Отметить доставленным', 'admin.noOrders': 'Заказов пока нет.', 'admin.note': 'Действия панели администратора сохраняются в браузере.', 'admin.listingActive': 'В каталоге', 'admin.listingPaused': 'Скрыто', 'admin.completeBooking': 'Отметить завершённым',

    'footer.tagline': 'Планируйте мероприятия легко и уверенно.', 'footer.explore': 'Каталог', 'footer.support': 'Помощь', 'footer.company': 'FESTIVO', 'footer.helpCenter': 'Центр помощи', 'footer.howWorks': 'Как это работает', 'footer.about': 'О нас', 'footer.terms': 'Условия использования', 'footer.privacy': 'Политика конфиденциальности', 'footer.contact': 'Контакты', 'footer.copyright': 'Все права защищены.', 'footer.madeWith': 'Создано с заботой о праздниках', 'footer.newsletter': 'Будьте в курсе новостей', 'footer.newsletterText': 'Новые предложения и полезные советы — иногда в вашей почте.', 'footer.emailPlaceholder': 'Ваша электронная почта', 'footer.subscribe': 'Подписаться', 'footer.newsletterSuccess': 'Спасибо за подписку!', 'legal.aboutTitle': 'О FESTIVO', 'legal.aboutText': 'FESTIVO — маркетплейс, который помогает находить, сравнивать и бронировать оборудование и услуги для мероприятий. Мы собрали местных партнёров, понятные цены и удобное планирование в одном месте.', 'legal.termsTitle': 'Условия использования', 'legal.termsText': 'FESTIVO предоставляет платформу для поиска и заказа товаров и услуг. После отправки заказа партнёр свяжется с вами, чтобы подтвердить наличие и детали доставки. В этой демонстрационной версии данные сохраняются только на вашем устройстве.', 'legal.privacyTitle': 'Политика конфиденциальности', 'legal.privacyText': 'Эта демонстрационная версия хранит профиль, корзину и заказы в памяти браузера. Данные не отправляются на сервер. В продуктовой версии будут доступны подробные правила защиты и удаления данных.', 'legal.helpTitle': 'Центр помощи', 'legal.helpText': 'Есть вопросы о заказе, выборе оборудования или плане мероприятия? Напишите команде FESTIVO — мы готовы помочь.', 'legal.contactEmail': 'hello@festivo.uz',

    'toast.added': 'Оборудование добавлено в корзину.', 'toast.removed': 'Оборудование удалено из корзины.', 'toast.bookingCreated': 'Заказ успешно создан.', 'toast.profileSaved': 'Профиль сохранён.', 'toast.listingAdded': 'Новое предложение добавлено.', 'toast.listingStatus': 'Статус предложения обновлён.', 'toast.bookingUpdated': 'Статус заказа обновлён.', 'toast.langChanged': 'Язык изменён.', 'toast.copied': 'Ссылка скопирована.', 'toast.newsletter': 'Спасибо за подписку!',

    'validation.name': 'Введите имя и фамилию.', 'validation.email': 'Укажите корректный адрес электронной почты.', 'validation.phone': 'Введите номер телефона.', 'validation.date': 'Выберите дату мероприятия.', 'validation.datePast': 'Дата должна быть сегодня или позже.', 'validation.quantity': 'Количество должно быть не меньше 1.', 'validation.terms': 'Примите условия, чтобы продолжить.', 'validation.price': 'Цена должна быть больше 0.', 'validation.category': 'Выберите категорию.', 'validation.listingTitle': 'Введите название оборудования.', 'validation.listingDescription': 'Добавьте описание оборудования.', 'validation.address': 'Введите адрес доставки.',
  },

  en: {
    'common.currency': 'UZS', 'common.perDay': '/ day', 'common.day': 'day', 'common.days': 'days', 'common.guest': 'guest', 'common.guests': 'guests', 'common.quantity': 'Quantity', 'common.date': 'Date', 'common.price': 'Price', 'common.total': 'Total', 'common.subtotal': 'Subtotal', 'common.delivery': 'Delivery', 'common.installation': 'Installation', 'common.continue': 'Continue', 'common.cancel': 'Cancel', 'common.remove': 'Remove', 'common.save': 'Save', 'common.close': 'Close', 'common.back': 'Back', 'common.seeAll': 'See all', 'common.search': 'Search', 'common.all': 'All', 'common.active': 'Active', 'common.paused': 'Paused', 'common.from': 'from', 'common.optional': 'optional', 'common.required': 'Required', 'common.browse': 'Browse', 'common.free': 'Free', 'common.items': 'items', 'common.item': 'item', 'common.details': 'Details', 'common.status': 'Status', 'common.perPerson': 'per person', 'common.available': 'Available', 'common.notAvailable': 'Unavailable', 'common.today': 'Today', 'common.goHome': 'Go to home', 'common.send': 'Send', 'common.update': 'Update', 'common.noData': 'No data yet', 'common.rating': 'Rating', 'common.reviews': 'reviews', 'common.menu': 'Menu', 'common.apply': 'Apply', 'common.count': 'items',

    'nav.home': 'Home', 'nav.equipment': 'Equipment', 'nav.services': 'Services', 'nav.planner': 'Plan an Event', 'nav.bookings': 'My Bookings', 'nav.cart': 'Cart', 'nav.account': 'Account', 'nav.vendor': 'Vendor dashboard', 'nav.admin': 'Admin dashboard', 'nav.signIn': 'Sign in', 'nav.menu': 'Open menu',
    'header.delivery': 'Delivery across Tashkent', 'header.member': 'A trusted partner for every event', 'header.language': 'Language',

    'hero.eyebrow': 'EVERYTHING FOR YOUR EVENT, IN ONE PLACE', 'hero.title': 'PLAN YOUR EVENT IN 10 MINUTES', 'hero.subtitle': 'Find the right equipment and services, choose your date, and plan with confidence.', 'hero.searchPlaceholder': 'Try sound equipment or decor', 'hero.searchButton': 'Browse Equipment', 'hero.date': 'Event date', 'hero.guests': 'Number of guests', 'hero.primaryCta': 'Browse Equipment', 'hero.secondaryCta': 'Plan an Event', 'hero.rating': 'Rated 4.9/5 by customers', 'hero.trust': 'Event planning, made easy', 'hero.trustNote': 'Vetted partners · Clear pricing · On-time delivery', 'hero.badgeOne': 'Event ready', 'hero.badgeTwo': 'Top pick',

    'home.categoriesEyebrow': 'FIND WHAT YOU NEED', 'home.categoriesTitle': 'The right fit for every event', 'home.categoriesText': 'Weddings, birthdays, or corporate gatherings — find the essentials in a few steps.', 'home.popularEyebrow': 'POPULAR PICKS', 'home.popularTitle': 'Most-booked equipment', 'home.popularText': 'Trusted, event-ready picks loved by local hosts.', 'home.viewAll': 'Browse all equipment', 'home.stepsEyebrow': 'HOW IT WORKS', 'home.stepsTitle': 'Easy to plan, unforgettable to celebrate', 'home.stepOneTitle': 'Choose', 'home.stepOneText': 'Find the equipment and services you need.', 'home.stepTwoTitle': 'Book', 'home.stepTwoText': 'Select a date, quantity, and delivery option.', 'home.stepThreeTitle': 'Enjoy your event', 'home.stepThreeText': 'Our partners bring everything on time.', 'home.bannerTitle': 'A great event starts with a great plan', 'home.bannerText': 'Bring sound, lighting, furniture, and decor together in one cart.', 'home.bannerCta': 'Start planning', 'home.reviewText': 'Booking was so easy. Everything arrived on time, and our celebration was wonderful!', 'home.reviewBy': 'Madina R.', 'home.reviewRole': 'Tashkent · birthday',

    'category.all': 'All categories', 'category.audio': 'Sound equipment', 'category.lighting': 'Lighting', 'category.furniture': 'Furniture', 'category.decor': 'Decor & stage', 'category.photo': 'Photo & video', 'category.catering': 'Guest services',

    'catalog.eyebrow': 'THE FESTIVO CATALOG', 'catalog.title': 'Event equipment', 'catalog.subtitle': 'Find the essentials for your event and book them at a great price.', 'catalog.searchPlaceholder': 'Search products or categories', 'catalog.searchButton': 'Search', 'catalog.filters': 'Filters', 'catalog.category': 'Category', 'catalog.maxPrice': 'Maximum price', 'catalog.priceAny': 'No limit', 'catalog.sort': 'Sort by', 'catalog.sortPopular': 'Most popular', 'catalog.sortLow': 'Price: low to high', 'catalog.sortHigh': 'Price: high to low', 'catalog.results': 'items found', 'catalog.showing': 'Showing', 'catalog.emptyTitle': 'No matches found', 'catalog.emptyText': 'Try changing your search or filters.', 'catalog.clearFilters': 'Clear filters', 'catalog.mobileFilters': 'Filters',

    'product.perDay': 'per day', 'product.addCart': 'Add to Cart', 'product.view': 'View details', 'product.details': 'About this item', 'product.includes': 'What’s included', 'product.specs': 'Specifications', 'product.pickup': 'Self pickup available', 'product.deliveryAvailable': 'Delivery available', 'product.chooseDate': 'Choose your event date', 'product.quantity': 'Quantity', 'product.rentalDays': 'Rental duration', 'product.chooseDateHint': 'Availability is checked for your selected date.', 'product.stock': 'sets available', 'product.vendor': 'Partner', 'product.reviews': 'customer reviews', 'product.startingAt': 'Price', 'product.location': 'Tashkent, Uzbekistan', 'product.guarantee': 'Delivered clean and in working order', 'product.backCatalog': 'Back to equipment', 'product.tagPopular': 'Popular', 'product.tagNew': 'New', 'product.share': 'Share', 'product.noDescription': 'More information about this item is coming soon.', 'product.deliveryNote': 'Delivery pricing is shown at checkout.',

    'services.eyebrow': 'EXTRA CONVENIENCE', 'services.title': 'Event services', 'services.subtitle': 'Add the help you need to your order and manage it all in one place.', 'services.deliveryTitle': 'Delivery', 'services.deliveryText': 'We bring your equipment to the event venue at the agreed time.', 'services.installTitle': 'Setup & installation', 'services.installText': 'Our specialists connect and set up your sound and lighting equipment.', 'services.supportTitle': 'Personal support', 'services.supportText': 'Our team is here to help with any planning questions.', 'services.browseCta': 'Browse equipment', 'services.priceNote': 'Final service pricing is calculated in your cart.',

    'planner.title': 'Let’s plan your event', 'planner.subtitle': 'Share a few details and we’ll suggest equipment that fits.', 'planner.step': 'Step 1', 'planner.eventType': 'What are you planning?', 'planner.selectEvent': 'Choose an event type', 'planner.date': 'Event date', 'planner.guests': 'Expected number of guests', 'planner.venue': 'Event location or venue', 'planner.venuePlaceholder': 'For example, Tashkent city', 'planner.cta': 'Find matching equipment', 'planner.note': 'You can update your plan later in the cart.', 'planner.wedding': 'Wedding', 'planner.birthday': 'Birthday', 'planner.corporate': 'Corporate event', 'planner.conference': 'Conference', 'planner.concert': 'Concert', 'planner.family': 'Family celebration',

    'cart.title': 'Your cart', 'cart.subtitle': 'Equipment selected for your event.', 'cart.emptyTitle': 'Your cart is empty for now', 'cart.emptyText': 'Browse the catalog and add equipment to see it here.', 'cart.browse': 'Browse Equipment', 'cart.summary': 'Order summary', 'cart.services': 'Additional services', 'cart.deliveryLabel': 'Delivery to your venue', 'cart.deliveryHint': 'We’ll bring equipment to your event location.', 'cart.installLabel': 'Setup & installation', 'cart.installHint': 'A specialist will connect and set up your equipment.', 'cart.deliveryFee': 'Delivery fee', 'cart.installFee': 'Setup service', 'cart.itemsTotal': 'Equipment subtotal', 'cart.checkout': 'Continue to checkout', 'cart.freeDelivery': 'Delivery is calculated during checkout.', 'cart.remove': 'Remove from cart', 'cart.eventDate': 'Event date', 'cart.rentalDays': 'Rental duration', 'cart.secure': 'Secure booking · no hidden fees', 'cart.editDate': 'Change date',

    'checkout.title': 'Checkout', 'checkout.subtitle': 'Add your contact and delivery details.', 'checkout.contactTitle': 'Contact information', 'checkout.fullName': 'Full name', 'checkout.email': 'Email address', 'checkout.phone': 'Phone number', 'checkout.address': 'Delivery address', 'checkout.eventDate': 'Event date', 'checkout.notes': 'Additional notes', 'checkout.notesPlaceholder': 'Anything we should know about delivery', 'checkout.summary': 'Your order', 'checkout.placeOrder': 'Place booking', 'checkout.consent': 'By confirming, you agree to our service terms.', 'checkout.requiredError': 'Please complete all required fields.', 'checkout.emailError': 'Enter a valid email address.', 'checkout.phoneError': 'Enter a valid phone number.', 'checkout.dateError': 'The event date must be today or later.', 'checkout.successTitle': 'Your booking is confirmed!', 'checkout.successText': 'Your partner will be in touch soon. Track your booking in your account.', 'checkout.orderNumber': 'Booking number', 'checkout.viewBookings': 'View my bookings', 'checkout.continueShopping': 'Continue shopping', 'checkout.deliveryMethod': 'Delivery method', 'checkout.deliveryAddress': 'Deliver to my venue', 'checkout.pickup': 'I’ll pick it up', 'checkout.installation': 'Add setup and installation',

    'bookings.title': 'My bookings', 'bookings.subtitle': 'All your bookings and their current status, in one place.', 'bookings.emptyTitle': 'No bookings yet', 'bookings.emptyText': 'Explore the catalog and start planning your first event.', 'bookings.browse': 'Browse Equipment', 'bookings.order': 'Booking', 'bookings.created': 'Created', 'bookings.eventDate': 'Event date', 'bookings.guests': 'Guests', 'bookings.viewDetails': 'View booking details', 'bookings.items': 'items', 'status.pending': 'Awaiting confirmation', 'status.confirmed': 'Confirmed', 'status.preparing': 'Preparing', 'status.delivered': 'Delivered', 'status.completed': 'Completed', 'status.cancelled': 'Cancelled',

    'account.title': 'Your account', 'account.subtitle': 'Manage your profile and bookings in one place.', 'account.profile': 'Profile information', 'account.signIn': 'Sign in to your account', 'account.createAccount': 'Create an account', 'account.welcome': 'Welcome, {name}!', 'account.savedProfile': 'Your profile details have been saved.', 'account.fullName': 'Full name', 'account.email': 'Email address', 'account.phone': 'Phone number', 'account.address': 'Address', 'account.orders': 'Bookings', 'account.notifications': 'Notifications', 'account.notificationsText': 'We’ll let you know when your booking status changes.', 'account.memberSince': 'On FESTIVO since', 'account.signInButton': 'Sign in', 'account.logout': 'Sign out', 'account.note': 'Demo account: profile details are saved on this device.', 'account.guest': 'Guest account', 'account.profileSaved': 'Profile saved',

    'vendor.title': 'Vendor dashboard', 'vendor.subtitle': 'Manage your equipment and keep track of bookings.', 'vendor.dashboard': 'Overview', 'vendor.addListing': 'Add a listing', 'vendor.addListingText': 'List your equipment and reach more event hosts.', 'vendor.listingName': 'Equipment name', 'vendor.listingCategory': 'Category', 'vendor.listingPrice': 'Daily rental price', 'vendor.listingDescription': 'Short description', 'vendor.descriptionPlaceholder': 'Key details about your equipment', 'vendor.addListingButton': 'Publish listing', 'vendor.myListings': 'My listings', 'vendor.available': 'Active listings', 'vendor.rented': 'Bookings', 'vendor.revenue': 'Estimated revenue', 'vendor.productStatus': 'Status', 'vendor.pause': 'Pause listing', 'vendor.activate': 'Activate listing', 'vendor.noListings': 'No listings yet. Add your first piece of equipment.', 'vendor.verification': 'Partner status', 'vendor.verified': 'Verified partner', 'vendor.orders': 'Bookings', 'vendor.saveListing': 'Save listing', 'vendor.help': 'Need help? The FESTIVO partner team is here for you.', 'vendor.noOrders': 'No new bookings yet.', 'vendor.created': 'Your new listing is now in the catalog.', 'vendor.userTitle': 'Partner listing', 'vendor.userDescription': 'New equipment or service.',

    'admin.title': 'Admin dashboard', 'admin.subtitle': 'Manage the FESTIVO marketplace.', 'admin.overview': 'Marketplace overview', 'admin.totalOrders': 'Bookings', 'admin.totalVendors': 'Partners', 'admin.totalListings': 'Active listings', 'admin.grossVolume': 'Booking volume', 'admin.recentOrders': 'Recent bookings', 'admin.manageListings': 'Catalog listings', 'admin.manageBookings': 'Manage bookings', 'admin.orderId': 'ID', 'admin.customer': 'Customer', 'admin.event': 'Event date', 'admin.payment': 'Total', 'admin.action': 'Action', 'admin.approve': 'Approve', 'admin.reject': 'Hide', 'admin.confirm': 'Confirm booking', 'admin.markDelivered': 'Mark as delivered', 'admin.noOrders': 'There are no bookings yet.', 'admin.note': 'Admin actions are saved in this browser.', 'admin.listingActive': 'Published', 'admin.listingPaused': 'Hidden', 'admin.completeBooking': 'Mark as completed',

    'footer.tagline': 'Plan your events with ease and confidence.', 'footer.explore': 'Explore', 'footer.support': 'Support', 'footer.company': 'FESTIVO', 'footer.helpCenter': 'Help center', 'footer.howWorks': 'How it works', 'footer.about': 'About us', 'footer.terms': 'Terms of service', 'footer.privacy': 'Privacy policy', 'footer.contact': 'Contact', 'footer.copyright': 'All rights reserved.', 'footer.madeWith': 'Made with care for every celebration', 'footer.newsletter': 'Get the latest', 'footer.newsletterText': 'Fresh picks and useful tips, delivered to your inbox from time to time.', 'footer.emailPlaceholder': 'Your email address', 'footer.subscribe': 'Subscribe', 'footer.newsletterSuccess': 'Thanks for subscribing!', 'legal.aboutTitle': 'About FESTIVO', 'legal.aboutText': 'FESTIVO is a marketplace for finding, comparing, and booking equipment and services for events. We bring local partners, clear pricing, and easy planning together in one place.', 'legal.termsTitle': 'Terms of service', 'legal.termsText': 'FESTIVO provides a platform to discover and book equipment and services. After you place a booking, the partner will contact you to confirm availability and delivery details. In this demo, information is saved on your device only.', 'legal.privacyTitle': 'Privacy policy', 'legal.privacyText': 'This demo stores your profile, cart, and bookings in your browser. Your data is not sent to a server. The production product will provide clear policies for protecting and deleting your data.', 'legal.helpTitle': 'Help center', 'legal.helpText': 'Questions about a booking, equipment, or event plan? Contact the FESTIVO team — we’re here to help.', 'legal.contactEmail': 'hello@festivo.uz',

    'toast.added': 'Equipment added to your cart.', 'toast.removed': 'Equipment removed from your cart.', 'toast.bookingCreated': 'Booking created successfully.', 'toast.profileSaved': 'Profile saved.', 'toast.listingAdded': 'New listing added.', 'toast.listingStatus': 'Listing status updated.', 'toast.bookingUpdated': 'Booking status updated.', 'toast.langChanged': 'Language updated.', 'toast.copied': 'Link copied.', 'toast.newsletter': 'Thanks for subscribing!',

    'validation.name': 'Enter your full name.', 'validation.email': 'Enter a valid email address.', 'validation.phone': 'Enter your phone number.', 'validation.date': 'Choose an event date.', 'validation.datePast': 'The date must be today or later.', 'validation.quantity': 'Quantity must be at least 1.', 'validation.terms': 'Please accept the terms to continue.', 'validation.price': 'Price must be greater than 0.', 'validation.category': 'Choose a category.', 'validation.listingTitle': 'Enter an equipment name.', 'validation.listingDescription': 'Add an equipment description.', 'validation.address': 'Enter a delivery address.',
  },
};

export const translationKeys = Object.keys(translations.uz);

export function translate(language, key, values = {}) {
  const selected = translations[language]?.[key] ?? translations.uz[key] ?? '';
  return selected.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? `{${name}}`));
}
